name: Test plugin - QGIS v3.x releases

# NOTE: remove this whole workflow file once we drop QGIS v3.x support

on:
  push:
    branches:
      - qgis-v3
    paths-ignore:
      - '*.md'
      - '*.sh'
      - '**/metadata.txt'
  workflow_dispatch:
  pull_request:
    branches:
      - qgis-v3

env:
  PLUGIN_PATH: valhalla

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        qgis_tags: [3.44.10]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: qgis-v3
          submodules: recursive

      - name: tests
        run: |
          docker pull qgis/qgis:${{ matrix.qgis_tags }}
          docker run -dt --name qgis-testing-environment --network host -v "${GITHUB_WORKSPACE}":/tests_directory -e QT_QPA_PLATFORM="offscreen" qgis/qgis:${{ matrix.qgis_tags }}

          # first run the docker/external valhalla_service tests
          docker run -dt --name valhalla-router -p 8002:8002 -v $PWD/tests/data:/custom_files -e tileset_name=andorra-tiles ghcr.io/valhalla/valhalla-scripted:latest
          sudo apt-get update && sudo apt-get install -y moreutils
          jq '.service_limits.status.allow_verbose = true' $PWD/tests/data/valhalla.json | sponge $PWD/tests/data/valhalla.json
          docker restart valhalla-router
          docker exec qgis-testing-environment bash -c "/tests_directory/tests/scripts/qgis_test_setup.sh ${{ matrix.qgis_tags }} ${{ env.PLUGIN_PATH }} tests/test_localhost_docker"

          # then with the plugin enabled and no external valhalla_service
          # the test setup will install the bindings to the right location
          docker stop valhalla-router
          docker exec qgis-testing-environment bash -c "/tests_directory/tests/scripts/qgis_test_setup.sh ${{ matrix.qgis_tags }} ${{ env.PLUGIN_PATH }} tests/test_localhost_plugin"
          # do the coverage
          docker exec qgis-testing-environment bash -c "cd /tests_directory && python3 -m coverage report && python3 -m coverage lcov --include \"valhalla/*\""
